### PR TITLE
Updating admin screen styles to match WordPress

### PR DESCRIPTION
**Pull request by webmandesign**
## CSS styles

As I haven't got the access to source preprocessor files, I've edited the `assets/css/main.css` file manually. Please update your preprocessor files accordingly if necessary.

### Example of multiple predefined demo imports, that a user can choose from:

Example of multiple predefined demo imports, that a user can choose from.

### How the import page looks like, when only one demo import is predefined:

How the import page looks like, when only one demo import is predefined.

### Example of how the import page looks like, when no demo imports are predefined a.k.a manual import:

Example of how the import page looks like, when no demo imports are predefined a.k.a manual import.

### CODE REVIEW

**Comment by webmandesign** [comment]
BTW, the CSS styles are now also RTL language ready (or rather language direction independent).

**Comment by primozcigler** [comment]
@webmandesign thank you for PR! It looks good to me. @capuderg will merge it after his code review.

**Comment by capuderg** [comment]
Hi @webmandesign,

thanks for this nice style change! I'm gonna merge this, but I will also make some small changes:
- remove indentation in main.css
- some small changes in main.css
- add two spaces between classes in HTML (that's what we prefer).

Also we do not have CSS preprocessor setup for this plugin, since there is very little CSS code.

If you plan on creating more PRs I would appreciate it, if you could open a issue first, so we can discuss it first. Don't get me wrong, you did a great job with this PR, it's just better, if we can discuss it first. :)

The only thing that I would like to improve in your new design is this block:

> A special note for this import

This block was meant to be a "warning", so it should stand out a bit. I agree a normal wp notice would not look good there. Do you have a proposal on how to make it stand out a bit, so users would not just ignore it, since right now, it's just a white block?

Thanks again and take care!

**Comment by webmandesign** [comment]
Hey, thank you for merging this! :)

`main.css`
I thought you are using some preprocessor as the file seemed to be formatted that way to me ;) So, sure, feel free to edit it to your coding standards and sorry for messing things up (with HTML `class` attribute as well).

If I have some more PRs for you I will open an issue first. It's just my way of work as I tend to discuss changes of PR directly in PR's comments. But I will open an issue for you from now on.

As for "A special note for this import" box, I haven't thought about this an a warning. I thought it is just a note where a theme author can provide **any** info about the demo so I didn't want to style it as warning. But if that's the case we can maybe just change its color. I suggest standard informative colors of blue. What do you say? Should I submit that color change or will you do it to your taste? Maybe we can use the same style as WordPress uses either for warning or info notices (with simple colored border on the left (right for RTL) edge)?

Regards,

Oliver

**Comment by capuderg** [comment]
Great! :)

I was thinking in the same way. Leave it as it is, but add a border to the left (or right for RTL) side. And as you said, we can use the blue "info" WP color.

If you could create a new PR with this change, that would be awesome! No need to create a new issue for this one :)

Have a great weekend Oliver!

**Comment by webmandesign** [comment]
PR #43 adding additional styles to resolve this. Have a nice weekend too, @capuderg !

**Comment by capuderg** [comment]
Merged! 👍 

Thanks again!

**Pull request merged**
